package microtrafficsim.osmcreator.user.controller;

/**
 * @author Dominic Parga Cacheiro
 */
public enum UserState {
  READY,
  READY_DILIGENT,
  SELECTION_ACTIVE,
  SELECTION_ACTIVE_DILIGENT,
  CROSSROADS_SELECTED,
  CROSSROADS_SELECTED_DILIGENT,
  MOVING_ACTIVE,
  MOVING_ACTIVE_DILIGENT,
  STREET_SELECTED,
  STREET_SELECTED_DILIGENT
}
